name: CI/CD Site HTML

on: 
  push:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Remove a instalação do Docker
      - name: Validar HTML com vnu
        run: docker run --rm -v ${{ github.workspace }}:/workspace ghcr.io/validator/validator:latest vnu --skip-non-html /workspace

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3
      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
